//Types for new meetup
export const ADD_MEETUP = 'ADD_MEETUP';
export const ADD_MEETUP_SUCCESS = 'ADD_MEETUP_SUCCESS';
export const ADD_MEETUP_ERROR = 'ADD_MEETUP_ERROR';

//Types for list meetup
export const BEGIN_DOWNLOAD_MEETUP = 'BEGIN_DOWNLOAD_MEETUP';
export const DOWNLOAD_MEETUP_SUCCESS = 'DOWNLOAD_MEETUP_SUCCESS';
export const DOWNLOAD_MEETUP_ERROR = 'DOWNLOAD_MEETUP_ERROR';

export const BEGIN_UPDATE_MEETUP = 'BEGIN_UPDATE_MEETUP';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_ERROR = 'UPDATE_ERROR';

export const GET_FAVORITE_MEETUP = 'GET_FAVORITE_MEETUP';
export const GET_FAVORITE_MEETUP_SUCCES = 'GET_FAVORITE_MEETUP_SUCCES';
export const GET_FAVORITE_MEETUP_ERROR = 'GET_FAVORITE_MEETUP_ERROR';

